### PR TITLE
Add new method int Transformer: commentModuleInProfile 

### PR DESCRIPTION
**Pull request by JiriOndrusek**
Addition of a new tranformer method:
- comments a module listed in the profile

### CODE REVIEW

**Comment by JiriOndrusek** [comment]
@ppalaga would it be possible to release this project with this update? I'd like to use the change in https://github.com/l2x6/cq-maven-plugin

**Comment by JiriOndrusek** [comment]
I forgot to create a test, I'll add it in a moment, sorry for that

**Comment by JiriOndrusek** [comment]
Test is there

**Review by cstamas — APPROVED** [review]

**Review by zhfeng — APPROVED** [review]

**Review by ppalaga — APPROVED** [review]
Thanks @JiriOndrusek!

**Comment by ppalaga** [comment]
@cstamas do you happen to have some more changes to add before we release 4.4.0?

**Comment by cstamas** [comment]
No, just got with the release

**Comment by ppalaga** [comment]
4.4.0 is in Central now https://repo1.maven.org/maven2/org/l2x6/pom-tuner/pom-tuner/4.4.0/pom-tuner-4.4.0.pom

**Comment by ppalaga** [comment]
Let me release 4.16.1

**Comment by ppalaga** [comment]
See https://github.com/l2x6/cq-maven-plugin/actions/runs/12295608334

**Pull request merged**
