### PR TITLE
JAXP0801002: the compiler encountered an XPath expression containing …

### PR DESCRIPTION
**Pull request by ppalaga**
…'101' operators that exceeds the '100' limit set by 'FEATURE_SECURE_PROCESSING' #20

### CODE REVIEW

**Comment by ppalaga** [comment]
I never saw this kind of issue before. 

@grgrzybek does this sound like a solution?

**Comment by grgrzybek** [comment]
Yes - but beware of CVE hunters ;)

**Comment by grgrzybek** [comment]
technically if there's XPath expression with >100 parameter, then it's obvious you need to evaluate it - it's not that you're parsing XML from malicious source...

**Comment by grgrzybek** [comment]
did you try with latest JDK 11.0.15.1? You should see it too...

**Pull request merged**
